lcd/urls.py
from django.urls import path
from . import views


app_name = 'lcd'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create', views.LcdCreate.as_view(), name='create'),
    path('update/<int:pk>', views.LcdUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.LcdDelete.as_view(), name='delete'),
]

lights/urls.py
from django.urls import path
from . import views


app_name = 'lights'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create', views.LightCreate.as_view(), name='create'),
    path('update/<int:pk>', views.LightUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.LightDelete.as_view(), name='delete'),
]

pi_traffic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('lights/', include('lights.urls', namespace='lights')),
    path('switches/', include('switches.urls', namespace='switches')),
    path('lcd/', include('lcd.urls', namespace='lcd')),
    path('admin/', admin.site.urls),
]

lights/models.py
from django.db import models


class TrackedModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Light(TrackedModel):
    color = models.CharField(max_length=255, help_text="This can be a color, or any description of the light, such as 'Yellow Arrow'")
    pin = models.IntegerField(help_text="BCM mode pin number of the switch.  Not the physical pin number.")
    delay = models.FloatField(help_text="Amount of time from the start of the cycle until this light turns on.")
    duration = models.FloatField(help_text="Length of time this light stays on after it comes on.")
    pull = models.BooleanField(default=False, verbose_name="Pull high", help_text="Check the box if the light should be pulled high when it is on.")

lights/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from lights.models import Light
from django.urls import reverse_lazy


class Index(ListView):
    template_name = 'lights/index.html'
    model = Light
    ordering = 'delay'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['page'] = 'lights'
        context['title'] = 'Light Index'
        lights = []
        return context


class LightCreate(CreateView):
    model = Light
    template_name = 'lights/create.html'
    fields = ['color', 'pin', 'delay', 'duration']
    success_url = reverse_lazy('lights:index')

    def get_context_data(self, **kwargs):
        context = super(LightCreate, self).get_context_data(**kwargs)
        context['title'] = 'Create Light'
        return context


class LightUpdate(UpdateView):
    model = Light
    template_name = 'lights/update.html'
    fields = ['color', 'pin', 'delay', 'duration']
    success_url = reverse_lazy('lights:index')

    def get_context_data(self, **kwargs):
        context = super(LightUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Update Light'
        return context


class LightDelete(DeleteView):
    model = Light
    template_name = 'lights/delete.html'
    success_url = reverse_lazy('lights:index')

    def get_context_data(self, **kwargs):
        context = super(LightDelete, self).get_context_data(**kwargs)
        context['title'] = 'Delete Light'
        return context

lights/templates/lights/create.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    <div class="container mt-5">
        <h2>Create Light</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock body %}

lights/templates/lights/delete.html
{% extends 'home/base.html' %}
{% block body %}
    <div class="container mt-5">
        <h2>Delete Light</h2>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete the "{{ object.color }}" light?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
    </div>
{% endblock body %}

lights/templates/lights/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid mt-5">
        <h2>Active Lights</h2>
        <div class="table-responsive">
            <table class="table table-bordered table-sm table-striped">
                <caption>List of lights</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Light</th>
                    <th>Pin</th>
                    <th>Delay</th>
                    <th>Duration</th>
                    <th>Pull Direction</th>
                    <th>&nbsp;</th>
                </thead>
                <tbody>
                </tr>
                {% for light in object_list %}
                    <tr>
                        <td>{{ light.color }}</td>
                        <td>{{ light.pin }}</td>
                        <td>{{ light.delay }}</td>
                        <td>{{ light.duration }}</td>
                        <td>{% if light.pull %}HIGH{% else %}LOW{% endif %}</td>
                        <td>
                            <button type="button" class="btn btn-primary"
                                    onclick="window.location='{% url 'lights:update' light.pk %}';">Update
                            </button>
                            <button type="button" class="btn btn-danger"
                                    onclick="window.location='{% url 'lights:delete' light.pk %}';">delete
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <button type="button" class="btn btn-info" onclick="window.location='{% url 'lights:create' %}';">Add New
        </button>
    </div>
{% endblock body %}

lights/templates/lights/update.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    <div class="container mt-5">
        <h2>Update Light</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
{% endblock body %}