home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

lcd/urls.py
from django.urls import path
from . import views


app_name = 'lcd'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create', views.LcdCreate.as_view(), name='create'),
    path('update/<int:pk>', views.LcdUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.LcdDelete.as_view(), name='delete'),
]

pi_traffic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('lights/', include('lights.urls', namespace='lights')),
    path('switches/', include('switches.urls', namespace='switches')),
    path('lcd/', include('lcd.urls', namespace='lcd')),
    path('admin/', admin.site.urls),
]

home/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['page'] = 'home'
        context['title'] = 'Home'
        return context

home/templates/home/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}">
    <meta charset="UTF-8">
    <title>Raspberry Pi Traffic Control - {{ title }}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'home:index' %}"><i class="fas fa-road"></i> <strong>Pi Traffic</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item{% if page == "home" %} active{% endif %}">
                <a class="nav-link" href="{% url 'home:index' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item{% if page == "lights" %} active{% endif %}">
                <a class="nav-link" href="{% url 'lights:index' %}"><i class="fas fa-traffic-light"></i> Lights</a>
            </li>
            <li class="nav-item{% if page == "switches" %} active{% endif %}">
                <a class="nav-link" href="{% url 'switches:index' %}"><i class="fab fa-nintendo-switch"></i> Switches</a>
            </li>
            <li class="nav-item{% if page == 'lcd' %} active{% endif %}">
                <a class="nav-link" href="{% url 'lcd:index' %}"><i class="fas fa-desktop"></i> LCDs</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock body %}
</div>
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% block script %}
{% endblock script %}
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid mt-5">
        <h2>Welcome to Pi Traffic</h2>
        <p>There are links across the top to change settings.&nbsp; Under the lights link, you configure the pins and
            lights you need for your particular traffic signal.&nbsp; You should have one light for each light you have
            connected to your pi.&nbsp; You should use the BCM mode pin number, and not the physical pin number, when
            setting the pins.&nbsp; You also need to know if your relay needs to be pulled high or low in order to turn
            the light on.&nbsp; Most solid relay modules are counterintuitively low when on, and high when off.&nbsp;
            You can control as many lights as you have GPIO pins on the pi with this.</p>
        <h2>Controlling Lights</h2>
        <p>When deciding the delay and duration, you need to understand that the lights go in a cycle.&nbsp; The timing
            is from the beginning of the entire cycle.&nbsp; For instance, on a five light system, you might want the
            green arrow to be on 10 seconds before the solid green light comes on, and you might want both of them to be
            on at the same time for a short period, but you want the green arrow to come on immediately.&nbsp; That
            means that your delay for the green arrow is 0, while the delay for the solid green light is 10.&nbsp;</p>
        <p>A sample set of values for a 5 light system might be as follows:</p>
        <table style="width: 100%; border-collapse: collapse; height: 108px;" border="1">
            <tbody>
            <tr style="height: 18px;">
                <th style="width: 20%; text-align: center; height: 18px;">Light</th>
                <th style="width: 20%; text-align: center; height: 18px;">Pin</th>
                <th style="width: 20%; text-align: center; height: 18px;">Delay</th>
                <th style="width: 20%; text-align: center; height: 18px;">Duration</th>
                <th style="width: 20%; text-align: center; height: 18px;">Pull</th>
            </tr>
            <tr style="height: 18px;">
                <td style="width: 20%; height: 18px;">Green Arrow</td>
                <td style="width: 20%; height: 18px;">18</td>
                <td style="width: 20%; height: 18px;">0.0</td>
                <td style="width: 20%; height: 18px;">10.0</td>
                <td style="width: 20%; height: 18px;">LOW</td>
            </tr>
            <tr style="height: 18px;">
                <td style="width: 20%; height: 18px;">Green</td>
                <td style="width: 20%; height: 18px;">17</td>
                <td style="width: 20%; height: 18px;">5.0</td>
                <td style="width: 20%; height: 18px;">25.0</td>
                <td style="width: 20%; height: 18px;">LOW</td>
            </tr>
            <tr style="height: 18px;">
                <td style="width: 20%; height: 18px;">Yellow Arrow</td>
                <td style="width: 20%; height: 18px;">15</td>
                <td style="width: 20%; height: 18px;">10.0</td>
                <td style="width: 20%; height: 18px;">5.0</td>
                <td style="width: 20%; height: 18px;">LOW</td>
            </tr>
            <tr style="height: 18px;">
                <td style="width: 20%; height: 18px;">Yellow</td>
                <td style="width: 20%; height: 18px;">4</td>
                <td style="width: 20%; height: 18px;">30.0</td>
                <td style="width: 20%; height: 18px;">5.0</td>
                <td style="width: 20%; height: 18px;">LOW</td>
            </tr>
            <tr style="height: 18px;">
                <td style="width: 20%; height: 18px;">Red</td>
                <td style="width: 20%; height: 18px;">27</td>
                <td style="width: 20%; height: 18px;">35.0</td>
                <td style="width: 20%; height: 18px;">38.0</td>
                <td style="width: 20%; height: 18px;">LOW</td>
            </tr>
            </tbody>
        </table>
        <p>You will notice that the delay shows the order in which they will turn on.&nbsp; The lower the delay, the
            sooner in the cycle the light will turn on.&nbsp; Once it is on, it will stay on as long as the duration is
            set.&nbsp; The duration starts from the time the light is turned on, not from the beginning of the cycle.&nbsp;
            That means, for instance, since the yellow arrow comes on at 10 seconds from the start of the cycle, due to
            its delay, it will shut off 15 seconds into the cycle, because it stays on for 5 seconds after the initial
            10 second wait to turn on.&nbsp; None of the lights rely on any other light to be on or off.</p>
        <p>With this kind of setup, even if you have a full intersection's worth of lights, even pedestrian signals, you
            can control them individually.</p>
        <h2>Controlling Switches</h2>
        <p>I have designed this to react to switch positions as well.&nbsp; Unfortunately, it has been necessary to hard
            code some of this into the program that does the actual work.&nbsp; That means that if you want to do
            different things than use a sensor to flash the lights on and off, you will need to modify the code.</p>
        <p>Currently, there are two switches.&nbsp; One is a mode switch that flips it between being a regular traffic
            signal and reacting to the other switch, which is a sound sensor.&nbsp; If you want to do more than that,
            you need to get your hands dirty and edit the code.</p>
        <h2>Future Intentions</h2>
        <p>In the future, I intend to allow some interaction with an LCD screen.&nbsp; I want to be able to change what
            is shown on the screen through this web interface.</p>
    </div>
{% endblock body %}