lcd/urls.py
from django.urls import path
from . import views


app_name = 'lcd'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create', views.LcdCreate.as_view(), name='create'),
    path('update/<int:pk>', views.LcdUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.LcdDelete.as_view(), name='delete'),
]

pi_traffic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('lights/', include('lights.urls', namespace='lights')),
    path('switches/', include('switches.urls', namespace='switches')),
    path('lcd/', include('lcd.urls', namespace='lcd')),
    path('admin/', admin.site.urls),
]

switches/urls.py
from django.urls import path
from . import views


app_name = 'switches'

urlpatterns = [
    path('', views.SwitchIndex.as_view(), name='index'),
    path('create', views.SwitchCreate.as_view(), name='create'),
    path('update/<int:pk>', views.SwitchUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.SwitchDelete.as_view(), name='delete'),
]

switches/models.py
from django.db import models


SWITCH_TYPES = [
    (0, 'Mode'),
    (1, 'Sound Sensor'),
]


class TrackedModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Switch(TrackedModel):
    name = models.CharField(max_length=200, help_text="Give a friendly name to this switch.")
    pin = models.IntegerField(help_text="GPIO Pin to look for.  This is in BCM mode.")
    pull = models.BooleanField(default=False, verbose_name="Pulls high", help_text="Check the box if the switch pulls the pin high when it is on.")
    on_name = models.CharField(max_length=255, help_text="Function when switch is on.", default="", blank=True)
    off_name = models.CharField(max_length=255, help_text="Function when switch is off.", default="", blank=True)
    switch_type = models.IntegerField(choices=SWITCH_TYPES, default=0)

switches/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Switch
from django.urls import reverse_lazy


class SwitchIndex(ListView):
    template_name = 'switches/index.html'
    model = Switch
    ordering = 'pk'

    def get_context_data(self, **kwargs):
        context = super(SwitchIndex, self).get_context_data(**kwargs)
        context['page'] = 'switches'
        context['title'] = 'Switch Index'
        if Switch.objects.count() >= 2:
            context['add_disabled'] = True
        return context


class SwitchCreate(CreateView):
    model = Switch
    template_name = 'switches/create.html'
    fields = ['name', 'pin', 'pull', 'on_name', 'off_name', 'switch_type']
    success_url = reverse_lazy('switches:index')

    def get_context_data(self, **kwargs):
        context = super(SwitchCreate, self).get_context_data(**kwargs)
        context['title'] = 'Create Switch'
        return context

    def form_valid(self, form):
        if form.cleaned_data['switch_type']:
            other_switch = 0
        else:
            other_switch = 1
        switches = Switch.objects.all().update(switch_type=other_switch)
        return super(SwitchCreate, self).form_valid(form)


class SwitchUpdate(UpdateView):
    model = Switch
    template_name = 'switches/update.html'
    fields = ['name', 'pin', 'pull', 'on_name', 'off_name', 'switch_type']
    success_url = reverse_lazy('switches:index')

    def get_context_data(self, **kwargs):
        context = super(SwitchUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Update Switch'
        return context

    def form_valid(self, form):
        if form.cleaned_data['switch_type']:
            other_switch = 0
        else:
            other_switch = 1
        Switch.objects.all().exclude(pk=self.kwargs['pk']).update(switch_type=other_switch)
        return super(SwitchUpdate, self).form_valid(form)


class SwitchDelete(DeleteView):
    model = Switch
    template_name = 'switches/delete.html'
    success_url = reverse_lazy('switches:index')

    def get_context_data(self, **kwargs):
        context = super(SwitchDelete, self).get_context_data(**kwargs)
        context['title'] = 'Delete Switch'
        return context

switches/templates/switches/create.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    <div class="container mt-5">
        <h2>Create Switch</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock body %}

switches/templates/switches/delete.html
{% extends 'home/base.html' %}
{% block body %}
    <div class="container mt-5">
        <h2>Delete Switch</h2>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete the "{{ object.name }}" switch?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
    </div>
{% endblock body %}

switches/templates/switches/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid mt-5">
        <h2>Switch Settings</h2>
        <table class="table table-bordered table-sm table-striped">
            <caption>List of switches</caption>
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Pin</th>
                <th>Pull Direction when on</th>
                <th>On Name</th>
                <th>Off Name</th>
                <th>Switch Type</th>
                <th>&nbsp;</th>
            </thead>
            <tbody>
            </tr>
            {% for switch in object_list %}
                <tr>
                    <td>{{ switch.name }}</td>
                    <td>{{ switch.pin }}</td>
                    <td>{% if switch.pull %}HIGH{% else %}LOW{% endif %}</td>
                    <td>{{ switch.on_name }}</td>
                    <td>{{ switch.off_name }}</td>
                    <td>{{ switch.get_switch_type_display }}</td>
                    <td>
                        <button type="button" class="btn btn-primary"
                                onclick="window.location='{% url 'switches:update' switch.pk %}';">Update
                        </button>
                        <button type="button" class="btn btn-danger"
                                onclick="window.location='{% url 'switches:delete' switch.pk %}';">delete
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="button" class="btn btn-info" onclick="window.location='{% url 'switches:create' %}';"{% if add_disabled %} disabled{% endif %}>Add New
        </button>
    </div>
{% endblock body %}

switches/templates/switches/update.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    <div class="container mt-5">
        <h2>Update Switch</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
{% endblock body %}