lcd/urls.py
from django.urls import path
from . import views


app_name = 'lcd'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create', views.LcdCreate.as_view(), name='create'),
    path('update/<int:pk>', views.LcdUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.LcdDelete.as_view(), name='delete'),
]

pi_traffic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('lights/', include('lights.urls', namespace='lights')),
    path('switches/', include('switches.urls', namespace='switches')),
    path('lcd/', include('lcd.urls', namespace='lcd')),
    path('admin/', admin.site.urls),
]

lcd/models.py
from django.db import models

LINE_CHOICES = [
    (1, 'Line 1'),
    (2, 'Line 2'),
]


class TrackedModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Lcd(TrackedModel):
    active = models.BooleanField(verbose_name='Make active screen', default=True, help_text="When checked, this will be the only active LCD.")
    line_1 = models.CharField(max_length=255, verbose_name='Line 1 text', blank=True, null=False, help_text="This text will be displayed as long as you don't override it with an IP address or mode below.")
    line_2 = models.CharField(max_length=255, verbose_name='Line 2 text', blank=True, null=False, help_text="This text will be displayed as long as you don't override it with an IP address or mode below.")
    show_ip = models.BooleanField(verbose_name='Show IP address', default=True, help_text="When checked, this shows the current IP address on the line chosen for the IP address below.")
    ip_line = models.IntegerField(choices=LINE_CHOICES, verbose_name='Line for IP address', default=1, help_text="Which line shows the IP address when above box is checked?")
    show_mode = models.BooleanField(verbose_name='Display mode', default=True, help_text="When checked, this shows the current mode the switch is in on the line chosen for the mode chosen below.")
    mode_line = models.IntegerField(choices=LINE_CHOICES, verbose_name='Line for mode', default=2, help_text="Which line shows the mode if box is checked?")
    power_switch_pin = models.IntegerField(blank=True, null=True, help_text="GPIO pin that turns the LCD on and off.  No pin will be chosen if left blank.")

lcd/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from lcd.models import Lcd
from django.urls import reverse_lazy
import socket


# This can be imported from controller.main, but I decided to hard copy it here so it won't cause conflicts
# if someone wants to use a database other than postgresql, although that means that the database will need to be
# changed in main.py as well.
def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    # Change port to a port that you do not have in use.
    s.connect(("8.8.8.8", 8080))
    ip = s.getsockname()[0]
    s.close()
    return ip


class Index(ListView):
    template_name = 'lcd/index.html'
    model = Lcd
    ordering = 'pk'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['page'] = 'lcd'
        context['title'] = 'lcd Index'
        return context


class LcdCreate(CreateView):
    model = Lcd
    template_name = 'lcd/create.html'
    fields = ['active', 'line_1', 'line_2', 'show_ip', 'ip_line', 'show_mode', 'mode_line', 'power_switch_pin']
    success_url = reverse_lazy('lcd:index')

    def get_context_data(self, **kwargs):
        context = super(LcdCreate, self).get_context_data(**kwargs)
        context['title'] = 'Create lcd'
        context['ip'] = get_ip_address()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if form.cleaned_data['active']:
            existing = Lcd.objects.all()
            if existing.first():
                Lcd.objects.exclude(pk=self.kwargs['pk']).update(active=False)
            Lcd.objects.exclude(pk=self.kwargs['pk']).update(active=False)
        if form.cleaned_data['show_ip']:
            if form.cleaned_data['ip_line'] == 1:
                self.object.line_1 = "IP Address: " + get_ip_address()
            else:
                self.object.line_2 = "IP Address: " + get_ip_address()
        if form.cleaned_data['show_mode']:
            if form.cleaned_data['mode_line'] == 1:
                self.object.line_1 = "Mode"
            else:
                self.object.line_2 = "Mode"
        self.object.save()
        return super(LcdCreate, self).form_valid(form)


class LcdUpdate(UpdateView):
    model = Lcd
    template_name = 'lcd/update.html'
    fields = ['active', 'line_1', 'line_2', 'show_ip', 'ip_line', 'show_mode', 'mode_line', 'power_switch_pin']
    success_url = reverse_lazy('lcd:index')

    def get_context_data(self, **kwargs):
        context = super(LcdUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Update lcd'
        context['ip'] = get_ip_address()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if form.cleaned_data['active']:
            Lcd.objects.exclude(pk=self.kwargs['pk']).update(active=False)
        if form.cleaned_data['show_ip']:
            if form.cleaned_data['ip_line'] == 1:
                self.object.line_1 = "IP Address: " + get_ip_address()
            else:
                self.object.line_2 = "IP Address: " + get_ip_address()
        if form.cleaned_data['show_mode']:
            if form.cleaned_data['mode_line'] == 1:
                self.object.line_1 = "Mode: Traffic/Music"
            else:
                self.object.line_2 = "Mode: Traffic/Music"
        self.object.save()
        return super(LcdUpdate, self).form_valid(form)


class LcdDelete(DeleteView):
    model = Lcd
    template_name = 'lcd/delete.html'
    success_url = reverse_lazy('lcd:index')

    def get_context_data(self, **kwargs):
        context = super(LcdDelete, self).get_context_data(**kwargs)
        context['title'] = 'Delete lcd'
        return context

lcd/templates/lcd/create.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    <div class="container mt-5">
        <h2>Create LCD</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock body %}
{% block script %}
<script>
$(document).ready(function() {
    $("#id_ip_line").change(function () {
        if ($(this).val() === '2') {
            $("#id_mode_line").val('1');
        } else {
            $("#id_mode_line").val('2');
        }
    });
    $("#id_mode_line").change(function () {
        if ($(this).val() === '2') {
            $("#id_ip_line").val('1');
        } else {
            $("#id_ip_line").val('2');
        }
    });
    if ($("#id_show_ip:checkbox").prop('checked')) {
        $("#id_line_" + $("#id_ip_line").val()).attr("disabled", true).val("IP Address: {{ ip }}");
    } else {
        $("#id_line_" + $("#id_ip_line").val()).attr("disabled", false);
    }
    if ($("#id_show_mode:checkbox").prop('checked')) {
        $("#id_line_" + $("#id_mode_line").val()).attr("disabled", true).val("Mode:  Traffic/Music");
    } else {
        $("#id_line_" + $("#id_mode_line").val()).attr("disabled", false);
    }
    $("#id_show_ip:checkbox ").change(function () {
        console.log($(this).prop('checked'));
        if ($(this).prop('checked')) {
            $("#id_line_" + $("#id_ip_line").val()).val('IP Address:  {{ ip }}').attr("disabled", true);
        } else {
            $("#id_line_" + $("#id_ip_line").val()).val('').attr("disabled", false);
        }
    });
    $("#id_show_mode:checkbox ").change(function () {
        console.log($(this).prop('checked'));
        if ($(this).prop('checked')) {
            $("#id_line_" + $("#id_mode_line").val()).val('Mode: Traffic/Music').attr("disabled", true);
        } else {
            $("#id_line_" + $("#id_mode_line").val()).val('').attr("disabled", false);
        }
    });
});
</script>
{% endblock script %}

lcd/templates/lcd/delete.html
{% extends 'home/base.html' %}
{% block body %}
    <div class="container mt-5">
        <h2>Delete LCD</h2>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete the settings for this LCD?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
    </div>
{% endblock body %}

lcd/templates/lcd/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid mt-5">
        <h2>LCD Settings</h2>
        <div class="table-responsive">
            <table class="table table-bordered table-sm table-striped">
                <caption>LCD Settings</caption>
                <thead class="thead-dark">
                <tr>
                    <th>Active</th>
                    <th>Line 1</th>
                    <th>Line 2</th>
                    <th>Show IP</th>
                    <th>IP Line</th>
                    <th>Show Mode</th>
                    <th>Mode Line</th>
                    <th>Power Pin</th>
                    <th>&nbsp;</th>
                </thead>
                <tbody>
                </tr>
                {% for lcd in object_list %}
                    <tr>
                        <td>{{ lcd.active }}</td>
                        <td>{{ lcd.line_1 }}</td>
                        <td>{{ lcd.line_2 }}</td>
                        <td>{{ lcd.show_ip }}</td>
                        <td>{{ lcd.ip_line }}</td>
                        <td>{{ lcd.show_mode }}</td>
                        <td>{{ lcd.mode_line }}</td>
                        <td>{{ lcd.power_switch_pin }}</td>
                        <td>
                            <button type="button" class="btn btn-primary"
                                    onclick="window.location='{% url 'lcd:update' lcd.pk %}';">Update
                            </button>
                            <button type="button" class="btn btn-danger"
                                    onclick="window.location='{% url 'lcd:delete' lcd.pk %}';">delete
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <button type="button" class="btn btn-info" onclick="window.location='{% url 'lcd:create' %}';">Add New
        </button>
    </div>
{% endblock body %}

lcd/templates/lcd/update.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
    <div class="container mt-5">
        <h2>Update LCD</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
{% endblock body %}
{% block script %}
<script>
$(document).ready(function() {
    const ip_line = $("#id_ip_line");
    const mode_line = $("#id_mode_line");

    ip_line.change(function () {
        if ($(this).val() === '2') {
            mode_line.val('1');
        } else {
            mode_line.val('2');
        }
    });
    mode_line.change(function () {
        if ($(this).val() === '2') {
            ip_line.val('1');
        } else {
            ip_line.val('2');
        }
    });
    if ($("#id_show_ip:checkbox").prop('checked')) {
        $("#id_line_" + ip_line.val()).attr("disabled", true).val("IP Address: {{ ip }}");
    } else {
        $("#id_line_" + ip_line.val()).attr("disabled", false);
    }
    if ($("#id_show_mode:checkbox").prop('checked')) {
        $("#id_line_" + mode_line.val()).attr("disabled", true).val("Mode:  Traffic/Music");
    } else {
        $("#id_line_" + mode_line.val()).attr("disabled", false);
    }
    $("#id_show_ip:checkbox ").change(function () {
        console.log($(this).prop('checked'));
        if ($(this).prop('checked')) {
            $("#id_line_" + ip_line.val()).val('IP Address:  {{ ip }}').attr("disabled", true);
        } else {
            $("#id_line_" + ip_line.val()).val('').attr("disabled", false);
        }
    });
    $("#id_show_mode:checkbox ").change(function () {
        console.log($(this).prop('checked'));
        if ($(this).prop('checked')) {
            $("#id_line_" + mode_line.val()).val('Mode: Traffic/Music').attr("disabled", true);
        } else {
            $("#id_line_" + mode_line.val()).val('').attr("disabled", false);
        }
    });
});
</script>
{% endblock script %}